# Generated by Django 4.1.4 on 2023-01-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=55)),
                ('site_url', models.URLField()),
                ('username', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=55)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
